[package]
name = "bakery-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
sea-orm = { version = "0.10", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros"
] }
tokio = { version = "1.23", features = ["rt", "macros"] }
