version: "3"
services:
  postgres:
    image: postgres:15.1
    container_name: bakery-backend-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    volumes:
      - "postgres:${POSTGRES_CONTAINER_DATA}"

volumes:
  postgres:
